import {
  Box,
  Drawer,
  Grid,
  List,
  ListItem,
  ListItemIcon,
  ListItemText,
  Stack,
} from "@mui/material";

import Head from "next/head";
import styled from "styled-components";

export default function Home() {
  return (
    <>
      <Head>
        <title style={{ color: "red" }}>Whale Education </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icons/logos/LogoWhale.svg" />
      </Head>
      <Stack
        direction="row"
        justifyContent="flex-start"
        alignItems="flex-start"
        spacing={2}
      >
        <Box sx={{ width: "500px" }}>adsdsa</Box>
        <Box sx={{ width: "100%" }}>adsdsa</Box>
      </Stack>
    </>
  );
}
