import Head from "next/head";
import styled from "styled-components";
import { Header } from "../containers";

export default function Home() {
  return (
    <div>
      <Head>
        <title style={{ color: "red" }}>Whale Education </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icons/logos/LogoWhale.svg" />
      </Head>

      <Header />
    </div>
  );
}

const Wrapper = styled.div`
  color: red;
`;
